name: Generate GitHub Stats

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create assets directory
        run: mkdir -p assets

      - name: Generate Simple Stats SVG
        run: |
          # Cria a pasta assets se não existir
          mkdir -p assets
          
          # Cria SVG simples para estatísticas
          cat > assets/github-stats.svg << 'EOF'
          <svg xmlns="http://www.w3.org/2000/svg" width="400" height="200">
            <rect width="400" height="200" fill="#24292e"/>
            <text x="20" y="40" fill="#fff" font-family="Arial" font-size="16">GitHub Stats for 0rafae1</text>
            <text x="20" y="80" fill="#58a6ff" font-family="Arial" font-size="14">Updated: $(date +'%Y-%m-%d')</text>
            <text x="20" y="120" fill="#fff" font-family="Arial" font-size="12">Generated via GitHub Actions</text>
          </svg>
          EOF

          # Cria SVG simples para linguagens
          cat > assets/github-langs.svg << 'EOF'
          <svg xmlns="http://www.w3.org/2000/svg" width="400" height="200">
            <rect width="400" height="200" fill="#24292e"/>
            <text x="20" y="40" fill="#fff" font-family="Arial" font-size="16">Top Languages</text>
            <text x="20" y="80" fill="#58a6ff" font-family="Arial" font-size="14">JavaScript, HTML, CSS</text>
            <text x="20" y="120" fill="#fff" font-family="Arial" font-size="12">Updated: $(date +'%Y-%m-%d')</text>
          </svg>
          EOF

      - name: Commit and Push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/
          git diff --staged --quiet || git commit -m "chore: update github stats"
          git push
