name: Generate GitHub Stats

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.PAT_1 }}
          username: 0rafae1
          show_icons: true
          include_all_commits: true
          count_private: true
          theme: tokyonight
          output_dir: assets
          file_name: github-stats

      - name: Generate Top Languages Card
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.PAT_1 }}
          username: 0rafae1
          layout: compact
          langs_count: 6
          theme: tokyonight
          output_dir: assets
          file_name: github-langs

      - name: Commit and Push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/
          git commit -m "update stats" || echo "no changes"
          git push
