name: Generate GitHub Stats

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Stats with API
        run: |
          # Baixa as estatísticas via API com autenticação
          curl -s "https://api.github.com/users/0rafae1/repos?per_page=100" \
            -H "Authorization: token ${{ secrets.PAT_1 }}" \
            -H "Accept: application/vnd.github.v3+json" \
            > repos.json

      - name: Create SVG Stats (Exemplo simplificado)
        run: |
          # Cria um SVG simples com as estatísticas
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="200">
            <rect width="400" height="200" fill="#24292e"/>
            <text x="20" y="40" fill="#fff" font-family="Arial" font-size="16">GitHub Stats for 0rafae1</text>
            <text x="20" y="80" fill="#58a6ff" font-family="Arial" font-size="14">Generated via GitHub Actions</text>
            <text x="20" y="120" fill="#fff" font-family="Arial" font-size="12">Updated: $(date +"%Y-%m-%d %H:%M")</text>
          </svg>' > assets/github-stats.svg

      - name: Commit and Push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/
          git diff --staged --quiet || git commit -m "chore: update github stats"
          git push
