name: Generate GitHub Stats

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_1 }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g github-readme-stats

      - name: Generate GitHub Stats
        run: |
          github-readme-stats --token ${{ secrets.PAT_1 }} --username 0rafae1 --show-icons true --include-all-commits true --count-private true --theme tokyonight --output-dir assets --file-name github-stats.svg

      - name: Generate Top Languages Card
        run: |
          github-readme-stats --token ${{ secrets.PAT_1 }} --username 0rafae1 --layout compact --langs-count 6 --theme tokyonight --output-dir assets --file-name github-langs.svg

      - name: Commit and Push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/
          git diff --staged --quiet || git commit -m "Update GitHub stats [$(date +'%Y-%m-%d')]"
          git push
